apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-ingress-web
  namespace: test-app-{{.Env.NAMESPACE}}
  annotations:
    cert-manager.io/cluster-issuer: leetsencrypt-staging
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
    - host: testapp.k8s.devopsagent.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: todo-web
                port:
                  number: 80
  tls:
    - hosts:
      - testapp.k8s.devopsagent.de
      secretName: testapp-tls
