apiVersion: v1
kind: Service
metadata:
  name: todo-web
  namespace: todoapp-broken
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
      targetPort: 80
  selector:
    app: todo-web
