loki:
  schemaConfig:
    configs:
      - from: 2025-07-01
        object_store: azure
        store: tsdb
        schema: v13
        index:
          period: 24h
          prefix: index_
  auth_enabled: false
  deploymentMode: SingleBinary
  querier:
    max_concurrent: 4
  replicas: 1
  retention_period: 24h
  storage:
    type: azure
    azure:
      accountKey: "PLACEHOLDER-SA-KEY"
      accountName: "PLACEHOLDER-SA-NAME"
      connection_string: "PLACEHOLDER-CONNECTION-STRING"
      container_name: "loki"
      use_managed_identity: false
      request_timeout: 0
    tsdb_shipper:
      active_index_directory: /loki/index
      cache_location: /loki/index_cache
      cache_ttl: 24h
    bucketNames:
      admin: loki-admin
      chunks: loki-chunks
      ruler: loki-ruler
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory: /var/loki/rules
      admin_api_directory: /var/loki/admin
  ruler:
    alertmanager_url: http://prometheus-alertmanager:9093
    enable_api: true
    storage:
      azure:
        accountKey: "PLACEHOLDER-SA-KEY"
        account_key: "PLACEHOLDER-SA-KEY"
        accountName: "PLACEHOLDER-SA-NAME"
        account_name: "PLACEHOLDER-SA-NAME"
        connection_string: "PLACEHOLDER-CONNECTION-STRING"
        container_name: "loki"
        use_managed_identity: false
      bucketNames:
        admin: loki-admin
        chunks: loki-chunks
        ruler: loki-ruler
  singleBinary:
    persistence:
      enabled: true
    replicas: 1
  limits_config:
    ingestion_rate_mb: 20
    ingestion_burst_size_mb: 40
    max_streams_per_user: 50000
    max_entries_limit_per_query: 5000
    max_query_series: 1000
gateway:
  replicas: 3
  enabled: true
read:
  replicas: 3
test:
  enabled: false
write:
  replicas: 3
backend:
  replicas: 3
compactor:
  retention_enabled: false
lokiCanary:
  enabled: false
minio:
  enabled: false
extraVolumeMounts:
  - mountPath: /tmp
    name: temp-storage
  - mountPath: /data/loki/wal
    name: wal-storage
  - mountPath: /data/loki/compactor
    name: compactor-storage
extraVolumes:
  - emptyDir: {}
    name: temp-storage
  - emptyDir: {}
    name: wal-storage
  - emptyDir: {}
    name: compactor-storage
