apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-front
  namespace: monitoring
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
    - http:
        paths:
          - backend:
              service:
                name: grafana
                port:
                  number: 80
            path: /monitoring/
            pathType: Prefix
  tls:
    - hosts:
        - grafana.k8s.devopsagent.de
      secretName: grafana-tls
