apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki-sa
  namespace: monitoring
  annotations:
    azure.workload.identity/client-id: <LOKI-MIDEVOPSAGENT.CLIENTID>
    azure.workload.identity/use: "true"
