apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-sa
  namespace: monitoring
  annotations:
    azure.workload.identity/client-id: <MONITORING-MIDEVOPSAGENT.CLIENTID>
    azure.workload.identity/use: "true"
