apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-api-ingress
  namespace: todoapp-broken
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
    - host: temp1.k8s.devopsagent.de
    - http:
        paths:
          - backend:
              service:
                name: todo-web
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - temp1.k9s.devopsagent.de
      secretName: testapp-tls

