apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api
  namespace: todo-nodejs-mongo-aks
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      serviceAccountName: todo-api-sa
      containers:
        - name: todo-api
          image: {{.Env.SERVICE_API_IMAGE_NAME}}
          ports:
            - containerPort: 3100
          env:
            - name: AZURE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: todo-api-secret
                  key: AZURE_CLIENT_ID
            - name: AZURE_KEY_VAULT_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: todo-api-config
                  key: AZURE_KEY_VAULT_ENDPOINT
            - name: APPLICATIONINSIGHTS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: todo-api-secret
                  key: APPLICATIONINSIGHTS_CONNECTION_STRING
                  optional: false
            - name: AZURE_COSMOS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: todo-api-secret
                  key: AZURE_COSMOS_CONNECTION_STRING
                  optional: false
            - name: APPLICATIONINSIGHTS_ROLE_NAME
              valueFrom:
                configMapKeyRef:
                  key: APPLICATIONINSIGHTS_ROLE_NAME
                  name: todo-api-config
