apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-ingress-api
  namespace: todoapp-broken
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
    - host: temp1.k8s.devopsagent.de
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: todo-api
                port:
                  number: 80
  tls:
    - hosts:
        - testapp.k8s.devopsagent.de
      secretName: testapp-tls
