apiVersion: v1
kind: Service
metadata:
  name: todo-api
  namespace: todoapp-broken
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: http
      targetPort: 3100
    - port: 443
      name: https
      targetPort: 3100
  selector:
    app: todo-api
